version: "3.5"
services:
    php-mongo-web:
        env_file:
          - .docker.env
        build:
            context: build/php-mongo-web
            args:
                - WITH_XDEBUG=false
                - WITH_XDEBUG_PROFILE=false
        volumes:
            - ../:/var/hosting/phpmongoadmin:delegated
            - ./profile:/tmp/xdebug:rw
            - ../var/www:/var/www:rw
        environment:
            - XDEBUG_CONFIG
        ports:
            - "80:80"
