version: "3.5"
services:
    php-mongo-db:
        env_file:
          - .docker.env
        image: mongo:4.4.3
        networks:
            - database
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORDD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - mongo:/var/lib/mongo:delegated
            - ./phpmongoadmin-init.js:/docker-entrypoint-initdb/mongo-init.js:ro
            - ./build/php-mongo-web/config/mongod.conf:/etc/mongod.conf:rw
        ports:
            - "27017:27017"

    php-mongo-web:
        env_file:
          - .docker.env
        build:
            context: build/php-mongo-web
            args:
                - WITH_XDEBUG=${WITH_XDEBUG}
                - WITH_XDEBUG_PROFILE=${WITH_XDEBUG_PROFILE}
        networks:
            - database
        depends_on:
            - php-mongo-db
        volumes:
            - ../:/usr/share/phpMongoAdmin:delegated
            - ./profile:/tmp/xdebug:rw
        environment:
            - XDEBUG_CONFIG
        ports:
            - "80:80"
        command:
          - composer install

networks:
    database:
        driver: "bridge"
volumes:
    mongo:


